env:
  global:
  - secure: akGjf8thhzFMbN+deTvmEDWGOPacrCkq9LE/1Dv8It60zR1ci1kUqKJb9Dx1NE/uWa8nX9bD6+WMkQYhW5F8Y9jK4dAJX8gtC2RYHMVBYf1x2LurW3lD2+q8Ry6LEg0rIcAF2JOMg+9BoSmAM3A9YdKEvDOed/UueUcgbIEnjwYNrDUW8H5ShYYZZ78AuWv7VVzBicmgVqv3VeqmvAeiDWCbc4KCv8dMTR1DdVLTvtEa63fi0+hgO9X2O0t20Q/GUDOJ+jjWs1SGpTVarEfXVtJLlfu6xqa9MltRDkd8071PAbOeilpnq17O6zFBQ0Il391hdtNhjBnZ1m6I4UNmA7hvwjRIPXY9n/FYM+HypgaMdLrFLkKKs/9EjnKe98hoRpt5YPmAo7Uh/9RylADDqQPDW6Z9GtyYkbpbs2Jyit9pl1wTKv4NbPYv9vj0hMhEsLWsMw587UXr2r+H6/yOAf3gvYk1LzAwtCyw5el3152TA1tno45H28Y4FuBtVlKbyaXdVhZNyqQOvX+b0fk6dHWmI1RnbFfFOJeTKRl0WycltEcDKSuFQkMdyQ3cTOPvXEZXtayn2AM/4ecUPlyy9u1sCwIEOQpUh4FbLQmCVZnG7wRGgQvAacWMwHC6cx8gw7f07BYm2jOY0sipVRKivzR8T3kH/WGI9z1hWbKeLHc=
  - secure: oY0I8xy4bDXap4QCTo4eD2GyVYr6Hxm2XDNZ0XBvG61bXGvW0c0gnSNTiisbq/gs1ybpCXF+im9P50Ve8z6k9wi7sUNaGdVffBdpzkXYiy+PwAsreOt2OzlZX47V1CU2uo6NRXoDM8muKX3sasoJ4v7bWqw54keaSOwReWeTRBMwobZQLZb/umRPt30cYjv0IhPKKxGMhjJh5ubaexDybp8f5sqp9T/VqvYIu63U74ai9Gf12x937BXe//wiKoaQbSQXROXWQzYZqUQvyzX3KXcaK9lIMmMd0uahpNippOZqGPsKxidKn7QAZnhA3IK7x9HzYD0KEKJCcCH4xVhSLWyqWYexlAJbXbvlsHEsdeZoO6KdnE6cuTLFw4vVJGFdrk234cRqke+FmSTXhwggShM5gXs+eXZFSskS3yzEc411LKSsO0wVatFqIzq2Ld6LaUzsuA06haRDxqUSK96zKJ79Nd6OiUXeH3G3CNIsE6C6cOqANgCvEbqRZbr9sH6fol+in9cIwJ2ceET0oAiPHX9mDetp2spW5RsaI3HBq+aDtl2CwsCzubC2oaSplEVFO+LsTRXFP4Lwono4J9MU+Elgr6XidVkLbplS0+a55PnTbsbkjFWNw6evL4ts6ZUgjdIEAKUCLZEf3Dn7YoWiCU345ImdU3wYnNZVaYrDLBI=
  - secure: mivAl8iFOQcvL9LuOB0McjGaHJUVyrznybQto6VmIJ8m8lJaHw/68Vb+V8QA7vt9DHPLgN2/56cMYeVF6iWJioiWDFdJ/QTimJNZeB9euKBLGK0OS7hStCjvyxY41ucy6An2cfMfuWDVTzDhMEnlevTZ95l91yJHvR4wpbpQ8pIeJhHHZ0iXviOdR0UwB+N9Hf9i7lpjZSjK5vi9l5yY6V/eryzRZYwz+VlCkmMNmuPli258Y1XqsVvDNvnoJptYa+cCuG+1cm+GjZyH44JnhcWHUNuAEF5TXFS2gM+pELZ9rgs81REbyjmlLVl8H9LkLL729BhJSSwqyQIiDoSucCUDEYExlKSCB+vpIpHI61bLDk2lbDhVmSgVbAvuBtjfi/4VWsjcn6WKFsvCKLfeYcKl58taoJcDevM+fsLYHkH28dTX2bkbeLHz+Dca2IVYeXCgMXdolTg1lypAH6ePZ7i+3NT0M3qNManrD1GNxLkrYZ3q5C9MoC/a+bf0zVqaEpvJHSB025DDGkgzD3FO4/N73KLGn12Qn04pj4LUTCo21zB1oD3YTAY9v4jDbEnFwFM1qQZYvaYIvnlFq9JmR8eo9vSMbwfCmNZ6pP7OyXT6FWraQY+1zYdfLxhDi+1DR8k/sfHjfRxzs3vD/U8TuZdle0cgepIOzZghFP7kYFM=
  - secure: aVSEAQTx+JXTtLmTpc2SANL3X6LYZZksvF1YBiaPGbs6lfgC4PYyz4uRqSEqDoIQqsrTR4JaoWyXajKYnbWysdJYyyC7asl7xweRsDNUKSgSzUPXhn4zxlMXLgfXpKq+cSn8UcX+RZuv0Vw/ai4603n5dOz5ENmwxcpB6GxZzrOYCCwgRvTm4VowYgYsnzi6iQnIy3BpTh5unUCLRi+9il3Y0Lfr0yjsFTeB+ItV1TF+fBmLZ3TbTXJLJHSkuFn0Cil8b0eRgS9g0YtxGudk576ewU+AWuLkJuofzv1FB1IELpAJGl0RIJZ6cJsIWqKHKYz3cvAp7OnwGtq2007+7+qnYqB1E1BkyZ4YmCRCD1Bvd6mbc3roktQ1ligTSU25VXF/XVy7Jd8Op37QViTbmiywnhFU6fJGhUFzHtMtAnC/db4twPILpT8Y19GsbDGUOvPDHd1EU7kXwcVE0Rs/lCtPYFPhtqUCQhJJdTC/eq8I0v92XyOevP/XFwpKujNHIjBNEzcCrV6PzW1ac5QsteBtSY3KBP5/M+r/athAIEh6xI9cSkA4FRX80m7Zb68nMxg/sIjiL3JRcU0ZpDN/E+OwwhMg5Mqlv9ylWz+uyzNoqV4PK6Ov+0NrwSRqJGDlUroqWnqF4G2tCFDHN7SLIGCU01qgPWA56zOw8X7OEWo=

services:
- docker

before-install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

before-script:
  - docker build --target test --tag my-test-image .
  - docker build --tag $DOCKER_USERNAME/todo-app:latest --target production .

script:
  - docker run my-test-image tests/test_viewmodel.py
  - docker run my-test-image tests/test_integration.py
  - >
     docker run
     -e API_KEY=$API_KEY
     -e TOKEN=$TOKEN
     -e BOARD_ID=$BOARD_ID
     my-test-image tests/test_e2e.py

after-script:
  - docker push $DOCKER_USERNAME/todo-app:latest