services:
- docker

before-script:
  - docker build --target test --tag my-test-image .

script:
  - docker run my-test-image tests/test_viewmodel.py
  - docker run my-test-image tests/test_integration.py